pipeline{
	agent any
	stages{
		
		stage("One"){
			steps{
				echo 'Hello'
			}
			}
		stage("Two"){
			steps{
				input( 'Continues?')
			}
			}
		stage("Three"){
				when {
				    not {
				        branch "origin/master"
				    }
				}

			steps{
				echo 'Hello'
				echo "${GIT_BRANCH}"
			}
			}
		stage('Four'){
			    parallel{
			    	stage('Unit Test'){
			    		steps{
			    			 echo "Running Unit test"
			    			 	}
			    			    }
			    	stage('Integration test') {		             
			    		steps{
			    			 echo 'Running the integration test'
			    			    }
			    			    }
			    			}
		}
}
}